"""refresh token family and audit severity

Revision ID: 8e3134ab9679
Revises: 65849f86200f
Create Date: 2026-06-13 05:15:26.736124
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3134ab9679'
down_revision: str | None = '65849f86200f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default makes these NOT NULL adds safe on tables with existing rows.
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('severity', sa.String(length=16), nullable=False, server_default='info')
        )

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('family_id', sa.String(length=36), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('generation', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))
        batch_op.drop_column('generation')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
