"""Clinical-insight rule content (PA-11).

Static, deterministic, **rules-first** patient-education content keyed by
canonical biomarker. This is *configuration* — educational guidance reviewed
against ``policies.py`` (no diagnosis, no prescription, no dose change), NOT
text generated by an LLM at runtime. The optional AI layer may only *rephrase*
this content and must still pass ``guardrails.check_output``.

Language: Vietnamese-first (product audience). Every composed patient string
ends with ``policies.DISCLAIMER_VI`` (added by the service, not here).

⚠️ Educational content — pending clinician sign-off before production enablement.

Shape per biomarker:
    {
      "meaning": str,                    # what the marker reflects, plain language
      "lifestyle": tuple[str, ...],      # generic wellness actions (never dosing)
      "retest_weeks": int,               # suggested re-test interval
      "by_status": {                     # risk + priority per abnormal status
          "low"|"high"|"critical": {"risks": tuple[str,...], "priority": Priority}
      },
    }

``priority`` ∈ {"monitor" (🟢), "watch" (🟠), "see_doctor" (🔴)}.
"""

from __future__ import annotations

from typing import Literal, TypedDict

Priority = Literal["monitor", "watch", "see_doctor"]


class StatusContent(TypedDict):
    risks: tuple[str, ...]
    priority: Priority


class BiomarkerContent(TypedDict):
    meaning: str
    lifestyle: tuple[str, ...]
    retest_weeks: int
    by_status: dict[str, StatusContent]


# Map a stored HealthMetric.metric_type (free-form) to a content key. Lab-promoted
# rows already use canonical lab keys; manual metrics use the UI taxonomy.
METRIC_TYPE_ALIASES: dict[str, str] = {
    "glucose": "fasting_glucose",
    "blood_pressure_systolic": "blood_pressure",
    "blood_pressure_diastolic": "blood_pressure",
    "systolic_bp": "blood_pressure",
    "weight_kg": "weight",
    "waist": "waist_cm",
    "cholesterol": "total_cholesterol",
    "ldl_c": "ldl",
    "hdl_c": "hdl",
}


def content_key(metric_type: str) -> str:
    """Resolve a metric_type to its insight-content key."""
    key = (metric_type or "").strip().lower()
    return METRIC_TYPE_ALIASES.get(key, key)


# Generic safe fallback for biomarkers without bespoke content (no AC1 gaps).
_GENERIC: BiomarkerContent = {
    "meaning": "Chỉ số này phản ánh một khía cạnh sức khỏe của bạn.",
    "lifestyle": (
        "Duy trì lối sống lành mạnh: ăn cân đối, vận động đều đặn, ngủ đủ giấc.",
        "Uống thuốc đúng theo hướng dẫn của bác sĩ (nếu đang dùng).",
    ),
    "retest_weeks": 12,
    "by_status": {
        "low": {
            "risks": (
                "Khi chỉ số nằm ngoài khoảng tham chiếu, cơ thể có thể bị ảnh hưởng tùy mức độ.",
            ),
            "priority": "watch",
        },
        "high": {
            "risks": (
                "Khi chỉ số nằm ngoài khoảng tham chiếu, cơ thể có thể bị ảnh hưởng tùy mức độ.",
            ),
            "priority": "watch",
        },
        "critical": {
            "risks": ("Chỉ số đang ở mức cần lưu ý đặc biệt.",),
            "priority": "see_doctor",
        },
    },
}


# --------------------------------------------------------------------------- #
# Priority ~12 authored biomarkers. Risk lines use possibility language
# ("có thể", "nếu kéo dài") — never definitive diagnosis.
# --------------------------------------------------------------------------- #

CONTENT: dict[str, BiomarkerContent] = {
    "tsh": {
        "meaning": (
            "TSH là hormone điều hòa hoạt động của tuyến giáp. Chỉ số này giúp phản "
            "ánh tuyến giáp đang hoạt động mạnh hay yếu hơn bình thường."
        ),
        "lifestyle": (
            "Uống thuốc tuyến giáp đúng giờ và đúng hướng dẫn của bác sĩ (nếu đang dùng).",
            "Ngủ đủ giấc và hạn chế căng thẳng kéo dài.",
            "Tái khám nội tiết theo lịch hẹn.",
        ),
        "retest_weeks": 8,
        "by_status": {
            "low": {
                "risks": (
                    "Tim đập nhanh hoặc hồi hộp",
                    "Khó ngủ, bồn chồn",
                    "Loãng xương nếu kéo dài",
                ),
                "priority": "see_doctor",
            },
            "high": {
                "risks": (
                    "Mệt mỏi, cảm giác uể oải",
                    "Tăng cân, sợ lạnh",
                    "Da khô, táo bón nếu kéo dài",
                ),
                "priority": "watch",
            },
            "critical": {
                "risks": (
                    "Chỉ số tuyến giáp đang lệch nhiều so với bình thường",
                    "Có thể ảnh hưởng tới nhịp tim và chuyển hóa",
                ),
                "priority": "see_doctor",
            },
        },
    },
    "fasting_glucose": {
        "meaning": (
            "Đường huyết lúc đói phản ánh mức đường trong máu khi bạn chưa ăn. Đây là "
            "chỉ số quan trọng để theo dõi chuyển hóa đường."
        ),
        "lifestyle": (
            "Hạn chế đồ ngọt, nước ngọt và tinh bột tinh chế.",
            "Đi bộ 30 phút mỗi ngày.",
            "Ăn nhiều rau xanh và chất xơ.",
        ),
        "retest_weeks": 12,
        "by_status": {
            "low": {
                "risks": ("Chóng mặt, run tay", "Vã mồ hôi, mệt nếu hạ đường nhiều"),
                "priority": "watch",
            },
            "high": {
                "risks": (
                    "Khát nước, tiểu nhiều",
                    "Mệt mỏi",
                    "Nguy cơ ảnh hưởng mạch máu nếu kéo dài",
                ),
                "priority": "see_doctor",
            },
            "critical": {
                "risks": ("Đường huyết đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "hba1c": {
        "meaning": (
            "HbA1c phản ánh mức đường huyết trung bình trong khoảng 2–3 tháng gần đây, "
            "giúp đánh giá kiểm soát đường huyết theo thời gian."
        ),
        "lifestyle": (
            "Duy trì chế độ ăn ít đường, đủ chất xơ.",
            "Vận động đều đặn mỗi ngày.",
            "Theo dõi đường huyết tại nhà theo hướng dẫn.",
        ),
        "retest_weeks": 12,
        "by_status": {
            "high": {
                "risks": (
                    "Kiểm soát đường huyết chưa tốt trong vài tháng qua",
                    "Nguy cơ ảnh hưởng mắt, thận, thần kinh nếu kéo dài",
                ),
                "priority": "see_doctor",
            },
            "critical": {
                "risks": ("HbA1c đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "alt": {
        "meaning": (
            "ALT là một men gan. Khi tăng, thường gợi ý tế bào gan đang chịu áp lực "
            "hoặc bị kích thích."
        ),
        "lifestyle": (
            "Hạn chế rượu bia.",
            "Giảm đồ chiên rán, nhiều dầu mỡ.",
            "Duy trì cân nặng hợp lý và vận động đều.",
        ),
        "retest_weeks": 8,
        "by_status": {
            "high": {
                "risks": (
                    "Gan có thể đang chịu áp lực",
                    "Nếu kéo dài có thể ảnh hưởng chức năng gan",
                ),
                "priority": "watch",
            },
            "critical": {
                "risks": ("Men gan đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "ast": {
        "meaning": (
            "AST là một men gan (cũng có ở cơ tim và cơ). Tăng AST có thể gợi ý gan "
            "hoặc cơ đang chịu áp lực."
        ),
        "lifestyle": (
            "Hạn chế rượu bia.",
            "Ăn uống lành mạnh, ít dầu mỡ.",
            "Vận động vừa sức, tránh gắng sức quá mức trước khi xét nghiệm.",
        ),
        "retest_weeks": 8,
        "by_status": {
            "high": {
                "risks": ("Gan hoặc cơ có thể đang chịu áp lực",),
                "priority": "watch",
            },
            "critical": {
                "risks": ("Men gan đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "ldl": {
        "meaning": (
            "LDL là loại cholesterol thường được gọi là 'cholesterol xấu'. Mức cao có "
            "thể liên quan tới tích tụ mỡ trong thành mạch máu."
        ),
        "lifestyle": (
            "Giảm mỡ động vật, đồ chiên rán.",
            "Ăn nhiều rau xanh, cá, hạt.",
            "Đi bộ hoặc vận động đều đặn.",
        ),
        "retest_weeks": 12,
        "by_status": {
            "high": {
                "risks": (
                    "Tăng nguy cơ tích tụ mảng xơ vữa trong mạch máu nếu kéo dài",
                    "Liên quan tới sức khỏe tim mạch",
                ),
                "priority": "watch",
            },
            "critical": {
                "risks": ("LDL đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "total_cholesterol": {
        "meaning": (
            "Cholesterol toàn phần là tổng lượng cholesterol trong máu, phản ánh một "
            "phần sức khỏe mỡ máu và tim mạch."
        ),
        "lifestyle": (
            "Ăn ít chất béo bão hòa.",
            "Tăng rau xanh, chất xơ, cá.",
            "Vận động đều đặn.",
        ),
        "retest_weeks": 12,
        "by_status": {
            "high": {
                "risks": ("Liên quan tới nguy cơ tim mạch nếu kéo dài",),
                "priority": "watch",
            },
            "critical": {
                "risks": ("Cholesterol đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "hdl": {
        "meaning": (
            "HDL là cholesterol 'tốt', giúp dọn bớt cholesterol thừa khỏi mạch máu. "
            "Mức HDL cao thường có lợi cho tim mạch."
        ),
        "lifestyle": (
            "Tăng vận động thể lực đều đặn.",
            "Ăn chất béo lành mạnh (cá, dầu ô liu, hạt).",
            "Hạn chế hút thuốc.",
        ),
        "retest_weeks": 12,
        "by_status": {
            "low": {
                "risks": ("HDL thấp có thể làm giảm khả năng bảo vệ tim mạch",),
                "priority": "watch",
            },
            "critical": {
                "risks": ("HDL đang ở mức cần lưu ý",),
                "priority": "watch",
            },
        },
    },
    "triglyceride": {
        "meaning": (
            "Triglyceride là một loại mỡ trong máu. Mức cao thường liên quan tới chế "
            "độ ăn nhiều đường, tinh bột và rượu bia."
        ),
        "lifestyle": (
            "Hạn chế đường, nước ngọt và rượu bia.",
            "Giảm tinh bột tinh chế.",
            "Tăng vận động.",
        ),
        "retest_weeks": 12,
        "by_status": {
            "high": {
                "risks": ("Liên quan tới sức khỏe tim mạch và tụy nếu rất cao",),
                "priority": "watch",
            },
            "critical": {
                "risks": ("Triglyceride đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "blood_pressure": {
        "meaning": (
            "Huyết áp phản ánh áp lực máu lên thành mạch. Theo dõi huyết áp giúp bảo "
            "vệ tim, não và thận."
        ),
        "lifestyle": (
            "Giảm muối trong khẩu phần ăn.",
            "Vận động đều đặn, giữ cân nặng hợp lý.",
            "Hạn chế rượu bia và căng thẳng kéo dài.",
        ),
        "retest_weeks": 4,
        "by_status": {
            "low": {
                "risks": ("Chóng mặt, mệt khi huyết áp xuống thấp",),
                "priority": "monitor",
            },
            "high": {
                "risks": (
                    "Tạo áp lực lên tim và mạch máu",
                    "Nếu kéo dài có thể ảnh hưởng tim, não, thận",
                ),
                "priority": "see_doctor",
            },
            "critical": {
                "risks": ("Huyết áp đang ở mức cần lưu ý đặc biệt",),
                "priority": "see_doctor",
            },
        },
    },
    "weight": {
        "meaning": (
            "Cân nặng là một chỉ số theo dõi tổng thể. Thay đổi cân nặng có thể ảnh "
            "hưởng tới chuyển hóa đường và mỡ máu."
        ),
        "lifestyle": (
            "Ăn cân đối, đủ rau xanh và đạm.",
            "Vận động đều đặn 30 phút mỗi ngày.",
            "Ngủ đủ giấc.",
        ),
        "retest_weeks": 4,
        "by_status": {
            "high": {
                "risks": ("Cân nặng tăng có thể ảnh hưởng đường huyết và mỡ máu",),
                "priority": "monitor",
            },
            "low": {
                "risks": ("Sụt cân ngoài ý muốn nên được bác sĩ đánh giá",),
                "priority": "watch",
            },
        },
    },
    "waist_cm": {
        "meaning": (
            "Vòng eo phản ánh lượng mỡ tích tụ quanh bụng, có liên quan tới nguy cơ chuyển hóa."
        ),
        "lifestyle": (
            "Giảm đường và tinh bột tinh chế.",
            "Tăng vận động, đặc biệt bài tập toàn thân.",
            "Ăn nhiều chất xơ.",
        ),
        "retest_weeks": 8,
        "by_status": {
            "high": {
                "risks": ("Vòng eo lớn liên quan tới nguy cơ chuyển hóa và tim mạch",),
                "priority": "monitor",
            },
        },
    },
}


def get_content(metric_type: str) -> BiomarkerContent:
    """Return bespoke content for a metric, or the safe generic fallback."""
    return CONTENT.get(content_key(metric_type), _GENERIC)


# Generic per-status follow-up phrasing (combined with retest_weeks by the service).
FOLLOWUP_BY_PRIORITY: dict[Priority, str] = {
    "monitor": "Tiếp tục theo dõi và duy trì thói quen lành mạnh.",
    "watch": "Theo dõi và trao đổi với bác sĩ trong lần khám tới.",
    "see_doctor": "Bạn nên chủ động trao đổi với bác sĩ về chỉ số này.",
}

PRIORITY_LABEL_VI: dict[Priority, str] = {
    "monitor": "🟢 Chỉ cần duy trì",
    "watch": "🟠 Theo dõi",
    "see_doctor": "🔴 Cần trao đổi bác sĩ",
}
