#!/usr/bin/env python3
"""Generate smoke-test route list from the FastAPI OpenAPI schema.

Outputs a shell-sourceable file: scripts/smoke-routes.sh
Each route is a `check` call matching the CI workflow's check() function signature:
  check "<label>" "<url>" "<expected_status>" "<method>"

Rules:
- All routes expect 401 when called without auth (all routes require auth in this app).
- Public routes (/api/v1/health, /health) expect 200.
- Routes with path params get a sentinel placeholder ("_smoke_" or "1").
- Skips routes that would be too noisy or destructive (DELETE, sensitive writes).

Usage:
  cd backend
  python3 ../scripts/generate-smoke-routes.py > ../scripts/smoke-routes.sh
  # then source in CI workflow

CI workflow usage (see .github/workflows/ci.yml):
  source scripts/smoke-routes.sh
"""

from __future__ import annotations

import os
import re
import sys

# Bootstrap app in test mode (no real DB/AI needed)
os.environ.setdefault("MCP_DATABASE_URL", "sqlite:////tmp/smoke_gen.sqlite3")
os.environ.setdefault("MCP_ENV", "test")
os.environ.setdefault("MCP_AI_MODE", "mock")
os.environ.setdefault("MCP_OCR_MODE", "mock")
os.environ.setdefault("FEATURE_AI_ASSISTANT", "true")
os.environ.setdefault("FEATURE_OCR", "true")
os.environ.setdefault("FEATURE_AI_RECOMMENDATION", "true")
os.environ.setdefault("MCP_OCR_WORKER_ENABLED", "false")

# Must be run from backend/ directory
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))

from app.main import app  # noqa: E402

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

# Routes that are explicitly public (return 200 unauthenticated)
PUBLIC_PATHS = {"/api/v1/health", "/health", "/api/v1/info"}

# Methods to include in smoke tests (skip DELETE to avoid accidental data loss)
INCLUDED_METHODS = {"GET", "POST"}

# Path param placeholder — uses a value that won't accidentally match real IDs
PARAM_PLACEHOLDER = "_smoke_"

# Representative subset: one route per "area" for fast smoke, not exhaustive
SMOKE_COVERAGE_AREAS = [
    "/api/v1/health",
    "/api/v1/auth/login",
    "/api/v1/auth/me",
    "/api/v1/patients/{patient_id}/lab-batches",
    "/api/v1/patients/{patient_id}/lab-results/{result_id}/explanation",
    "/api/v1/lab-uploads",
    "/api/v1/patients/{patient_id}/lab-intelligence",
    "/api/v1/admin/labs/reclassify",
    "/api/v1/admin/users",
]


def normalize_path(path: str) -> str:
    """Replace {param} placeholders with sentinel value."""
    return re.sub(r"\{[^}]+\}", PARAM_PLACEHOLDER, path)


def label_for(method: str, path: str) -> str:
    """Human-readable label for smoke check output."""
    # Strip /api/v1 prefix for brevity
    short = re.sub(r"^/api/v1", "", path)
    short = re.sub(r"\{[^}]+\}", "{id}", short)
    return f"{method} {short}"


def main() -> None:
    schema = app.openapi()
    paths = schema.get("paths", {})

    lines: list[str] = [
        "# AUTO-GENERATED by scripts/generate-smoke-routes.py",
        "# DO NOT EDIT MANUALLY — re-run script after route changes",
        "# Source this file inside the CI smoke-test step.",
        "#",
        "# Requires: BASE_BE variable set to backend base URL",
        "#           check() function defined (supports 4-arg: desc url status method)",
        "",
    ]

    # Determine which paths to emit (coverage subset, preserving order)
    # First pass: emit coverage areas in declared order
    emitted: set[str] = set()

    for coverage_path in SMOKE_COVERAGE_AREAS:
        if coverage_path not in paths:
            continue
        path_item = paths[coverage_path]
        for method, op in path_item.items():
            if method.upper() not in INCLUDED_METHODS:
                continue
            is_public = coverage_path in PUBLIC_PATHS
            expected = "200" if is_public else "401"
            url_path = normalize_path(coverage_path)
            label = label_for(method.upper(), coverage_path)
            lines.append(
                f'check "{label:<50}" "$BASE_BE{url_path}" "{expected}" "{method.upper()}"'
            )
            emitted.add(f"{method.upper()}:{coverage_path}")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
