# AUTO-GENERATED by scripts/generate-smoke-routes.py
# DO NOT EDIT MANUALLY — re-run script after route changes
# Source this file inside the CI smoke-test step.
#
# Requires: BASE_BE variable set to backend base URL
#           check() function defined (supports 4-arg: desc url status method)

check "GET /health                                       " "$BASE_BE/api/v1/health" "200" "GET"
check "POST /auth/login                                  " "$BASE_BE/api/v1/auth/login" "401" "POST"
check "GET /auth/me                                      " "$BASE_BE/api/v1/auth/me" "401" "GET"
check "GET /patients/{id}/lab-batches                    " "$BASE_BE/api/v1/patients/_smoke_/lab-batches" "401" "GET"
check "GET /patients/{id}/lab-results/{id}/explanation   " "$BASE_BE/api/v1/patients/_smoke_/lab-results/_smoke_/explanation" "401" "GET"
check "POST /lab-uploads                                 " "$BASE_BE/api/v1/lab-uploads" "401" "POST"
check "POST /patients/{id}/lab-intelligence              " "$BASE_BE/api/v1/patients/_smoke_/lab-intelligence" "401" "POST"
check "POST /admin/labs/reclassify                       " "$BASE_BE/api/v1/admin/labs/reclassify" "401" "POST"
check "GET /admin/users                                  " "$BASE_BE/api/v1/admin/users" "401" "GET"
